"""The captioning engine: audio extraction, transcription, caption rules,
output writers, and optional burn-in.

Public interface -- other packages should import from here rather than
reaching into submodules directly, so the internal layout can shift
without breaking callers:

    from ash_captions.engine import (
        extract_audio, AudioExtractionError,
        Word, Segment, TranscriptionResult, Transcriber, WhisperTranscriber,
        TranscriptionError, TranscriptionCancelled,
        Card, build_cards,
        render_srt, write_srt, render_ass, write_ass, render_txt, write_txt, AssPreset, CLEAN, POP,
        probe_video, VideoInfo, ProbeError,
        select_punch_moments, build_punch_filter,
        select_sfx_hits, build_sfx_plan, SfxTrigger, SfxHit, SfxPlan,
        detect_nvenc, build_burn_command, burn_captions, BurnInError, BurnCancelled,
        active_processes, kill_active_processes,
    )
"""
from .audio import AudioExtractionError, DEFAULT_FFMPEG_PATH, extract_audio
from .ffmpeg_process import active_processes, kill_active_processes
from .matte import (
    MATTE_MODEL_FILENAME,
    MatteCancelled,
    MatteError,
    MatteResult,
    composite_filtergraph,
    ensure_matte_model,
    matte_model_path,
    render_matte,
    working_size,
)
from .probe import ProbeError, VideoInfo, ffprobe_beside, probe_video
from .punch import (
    MAX_DURATION_SECONDS,
    MIN_DURATION_SECONDS,
    PunchMode,
    PunchMoment,
    build_punch_filter,
    build_zoompan_filter,
    select_punch_moments,
)
from .burn import (
    BurnCancelled,
    BurnInError,
    available_encoders,
    build_burn_command,
    burn_captions,
    detect_nvenc,
    nvenc_encode_works,
    part_path_for,
    select_video_encoder,
)
from .rules import Card, build_cards
from .sfx import (
    MAX_HITS,
    SfxHit,
    SfxPlan,
    SfxTrigger,
    build_sfx_filter,
    build_plan as build_sfx_plan,
    select_sfx_hits,
)
from .transcribe import (
    Segment,
    Transcriber,
    TranscriptionCancelled,
    TranscriptionError,
    TranscriptionResult,
    WhisperTranscriber,
    Word,
)
from .writers import (
    CLEAN,
    POP,
    AssPreset,
    render_ass,
    render_srt,
    render_txt,
    write_ass,
    write_srt,
    write_txt,
)

__all__ = [
    "extract_audio",
    "AudioExtractionError",
    "DEFAULT_FFMPEG_PATH",
    "Word",
    "select_sfx_hits",
    "build_sfx_plan",
    "build_sfx_filter",
    "SfxTrigger",
    "SfxHit",
    "SfxPlan",
    "MAX_HITS",
    "Segment",
    "TranscriptionResult",
    "Transcriber",
    "WhisperTranscriber",
    "TranscriptionError",
    "TranscriptionCancelled",
    "Card",
    "build_cards",
    "render_srt",
    "write_srt",
    "render_ass",
    "write_ass",
    "render_txt",
    "write_txt",
    "AssPreset",
    "CLEAN",
    "POP",
    "detect_nvenc",
    "nvenc_encode_works",
    "probe_video",
    "MATTE_MODEL_FILENAME",
    "MatteCancelled",
    "MatteError",
    "MatteResult",
    "composite_filtergraph",
    "ensure_matte_model",
    "matte_model_path",
    "render_matte",
    "working_size",
    "ffprobe_beside",
    "VideoInfo",
    "ProbeError",
    "PunchMode",
    "PunchMoment",
    "MIN_DURATION_SECONDS",
    "MAX_DURATION_SECONDS",
    "select_punch_moments",
    "build_punch_filter",
    "build_zoompan_filter",
    "available_encoders",
    "select_video_encoder",
    "build_burn_command",
    "burn_captions",
    "part_path_for",
    "BurnInError",
    "BurnCancelled",
    "active_processes",
    "kill_active_processes",
]
